name: Documentation
on:
  push:
    tags:
      - "*"
    branches: [main, master]
permissions:
  contents: read
jobs:
  build:
    name: Build and publish documentation
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update
      - name: Setup Cpp
        uses: aminya/setup-cpp@1f17f92d6a52bfcb1a25348e2c526c2e5cbb1134 # v1.8.0
        with:
          clangtidy: true
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      - name: Install Docs
        run: |
          sudo apt-get install doxygen
          pip install -r requirements.txt  --require-hashes
      - name: configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
      - name: building
        run: |
          cmake --build build --config Debug --target doc_doxygen -j4
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@502048fbc429a8ac1d1823976874aa4e5be155fb # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./build/docs/doc_doxygen/html
