name: MacOS CI Test
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Cpp
        uses: aminya/setup-cpp@9bc9b8cd8a8d678f920e4e1e73f29da8010ced51 # v1.7.2
        with:
          clangtidy: true
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      - name: configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug" -DCREATE_DOCUMENTATION=OFF
      - name: building
        run: |
          cmake --build build --config Debug --target Catch_tests_run -j4
      - name: run unit tests
        working-directory: ./build/bin
        run: |
          ./Catch_tests_run
