name: Ubuntu CI Test
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: install
        run: sudo apt-get update
      - name: Setup Cpp
        uses: aminya/setup-cpp@1f17f92d6a52bfcb1a25348e2c526c2e5cbb1134 # v1.8.0
        with:
          clangtidy: true
      - name: configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On
      - name: building
        run: |
          cmake --build build --config Debug --target Catch_tests_run -j4
      - name: run unit tests
        working-directory: ./build/bin
        run: |
          ./Catch_tests_run
      - name: generate coverage
        working-directory: ./build
        run: |
          make cov
      - name: Install gcovr
        run: |
          pip install -r requirements.txt  --require-hashes
      - name: Generate JSON coverage report
        working-directory: ./build
        run: |
          gcovr -r .. . --filter ../src/ --txt-metric branch --cobertura > coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
