name: Windows CI Test
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      - name: configure
        run: |
          cmake -H"." -Bbuild -T host=x86 -A x64 -DCMAKE_BUILD_TYPE="Debug" -DCREATE_DOCUMENTATION=OFF
      - name: building
        run: |
          cmake --build build --config Debug --target Catch_tests_run -j4
      - name: run unit tests
        run: |
          cd build
          cd bin
          cd Debug
          .\Catch_tests_run.exe
