name: Windows CI Test
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      - name: configure
        run: |
          cmake -H"." -Bbuild -T host=x86 -A x64 -DCMAKE_BUILD_TYPE="Debug" -DCREATE_DOCUMENTATION=OFF
      - name: building
        run: |
          cmake --build build --config Debug --target Catch_tests_run -j4
      - name: run unit tests
        run: |
          cd build
          cd bin
          cd Debug
          .\Catch_tests_run.exe
